title: "Enough is Enough"
description: "A public pledge to move from accumulation to connection"
remote_theme: just-the-docs/just-the-docs

# Define nav manually
plugins:
#- jekyll-remote-theme
  - jekyll-seo-tag
